apiVersion: network-builder.eda.local/v1alpha1
kind: SubnetLibrary
metadata:
  name: example-subnetlibrary
  namespace: eda
spec:
  nodeSelector:
    - eda.nokia.com/role=leaf
  loginBanner: Hello EDA!
