---
anchors:
  thresholds-operstate: &thresholds-operstate
    - color: "#FF3154" # red
      level: 0
    - color: "#4BDD33" # green
      level: 1

  thresholds-traffic: &thresholds-traffic
    - color: "#bec8d2" # grey
      level: 0
    - color: "#4BDD33" # green
      level: 199999
    - color: "#FFFF00" # yellow
      level: 500000
    - color: "#FF8000" # orange
      level: 1000000
    - color: "#FF3154" # red
      level: 5000000

  label-config: &label-config
    separator: replace
    units: bps
    decimalPoints: 1
    valueMappings:
      - valueMax: 199999
        text: ""
      - valueMin: 10

cellIdPreamble: cell-

cells:
#### ISP ####

  isp-1:c1-1:
    dataRef: oper-state:isp1:1/1/c1/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:isp1-c1-1:
    dataRef: isp1:1/1/c1/1:out
    label: *label-config



#### RENO ###
  reno-e1:c1-1:
    dataRef: oper-state:reno-e1:1/1/c1/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e1-c1-1:
    dataRef: reno-e1:1/1/c1/1:out
    label: *label-config

  reno-e1:c2-1:
    dataRef: oper-state:reno-e1:1/1/c2/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e1-c2-1:
    dataRef: reno-e1:1/1/c2/1:out
    label: *label-config

  reno-e1:c3-1:
    dataRef: oper-state:reno-e1:1/1/c3/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e1-c3-1:
    dataRef: reno-e1:1/1/c3/1:out
    label: *label-config

  reno-e1:c10-1:
    dataRef: oper-state:reno-e1:1/1/c10/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e1-c10-1:
    dataRef: reno-e1:1/1/c10/1:out
    label: *label-config

  reno-e1:c11-1:
    dataRef: oper-state:reno-e1:1/1/c11/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e1-c11-1:
    dataRef: reno-e1:1/1/c11/1:out
    label: *label-config


  reno-e2:c1-1:
    dataRef: oper-state:reno-e2:1/1/c1/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e2-c1-1:
    dataRef: reno-e2:1/1/c1/1:out
    label: *label-config

  reno-e2:c2-1:
    dataRef: oper-state:reno-e2:1/1/c2/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e2-c2-1:
    dataRef: reno-e2:1/1/c2/1:out
    label: *label-config

  reno-e2:c3-1:
    dataRef: oper-state:reno-e2:1/1/c3/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e2-c3-1:
    dataRef: reno-e2:1/1/c3/1:out
    label: *label-config

  reno-e2:c5-1:
    dataRef: oper-state:reno-e2:1/1/c5/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e2-c5-1:
    dataRef: reno-e2:1/1/c5/1:out
    label: *label-config

  reno-e2:c10-1:
    dataRef: oper-state:reno-e2:1/1/c10/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e2-c10-1:
    dataRef: reno-e2:1/1/c10/1:out
    label: *label-config

  reno-e2:c11-1:
    dataRef: oper-state:reno-e2:1/1/c11/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:reno-e2-c11-1:
    dataRef: reno-e2:1/1/c11/1:out
    label: *label-config

#### VEGAS ####

  vegas-e1:c1-1:
    dataRef: oper-state:vegas-e1:1/1/c1/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e1-c1-1:
    dataRef: vegas-e1:1/1/c1/1:out
    label: *label-config

  vegas-e1:c2-1:
    dataRef: oper-state:vegas-e1:1/1/c2/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e1-c2-1:
    dataRef: vegas-e1:1/1/c2/1:out
    label: *label-config

  vegas-e1:c3-1:
    dataRef: oper-state:vegas-e1:1/1/c3/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e1-c3-1:
    dataRef: vegas-e1:1/1/c3/1:out
    label: *label-config

  vegas-e1:c10-1:
    dataRef: oper-state:vegas-e1:1/1/c10/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e1-c10-1:
    dataRef: vegas-e1:1/1/c10/1:out
    label: *label-config

  vegas-e1:c11-1:
    dataRef: oper-state:vegas-e1:1/1/c11/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e1-c11-1:
    dataRef: vegas-e1:1/1/c11/1:out
    label: *label-config


  vegas-e2:c1-1:
    dataRef: oper-state:vegas-e2:1/1/c1/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e2-c1-1:
    dataRef: vegas-e2:1/1/c1/1:out
    label: *label-config

  vegas-e2:c2-1:
    dataRef: oper-state:vegas-e2:1/1/c2/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e2-c2-1:
    dataRef: vegas-e2:1/1/c2/1:out
    label: *label-config

  vegas-e2:c3-1:
    dataRef: oper-state:vegas-e2:1/1/c3/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e2-c3-1:
    dataRef: vegas-e2:1/1/c3/1:out
    label: *label-config

  vegas-e2:c5-1:
    dataRef: oper-state:vegas-e2:1/1/c5/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e2-c5-1:
    dataRef: vegas-e2:1/1/c5/1:out
    label: *label-config

  vegas-e2:c10-1:
    dataRef: oper-state:vegas-e2:1/1/c10/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e2-c10-1:
    dataRef: vegas-e2:1/1/c10/1:out
    label: *label-config

  vegas-e2:c11-1:
    dataRef: oper-state:vegas-e2:1/1/c11/1
    fillColor:
      thresholds: *thresholds-operstate
  label-link:vegas-e2-c11-1:
    dataRef: vegas-e2:1/1/c11/1:out
    label: *label-config

