# Alarm names (by intent)
# core
TOPO_LINK_DEGRADED = 'TopoLinkDegraded'
TOPO_LINK_DOWN = 'TopoLinkDown'

# protocols
DEFAULT_BGPPEER_DOWN = 'DefaultBGPPeerDown'
DEFAULT_BGPPEER_DEGRADED = 'DefaultBGPPeerDegraded'
BGPPEER_DOWN = 'BGPPeerDown'
BGPPEER_DEGRADED = 'BGPPeerDegraded'
DEFAULT_OSPFINSTANCE_DOWN = 'DefaultOSPFInstanceDown'
DEFAULT_OSPFINSTANCE_DEGRADED = 'DefaultOSPFInstanceDegraded'
DEFAULT_OSPFINTERFACE_DOWN = 'DefaultOSPFInterfaceDown'
DEFAULT_OSPFINTERFACE_DEGRADED = 'DefaultOSPFInterfaceDegraded'
OSPFINSTANCE_DOWN = 'OSPFInstanceDown'
OSPFINSTANCE_DEGRADED = 'OSPFInstanceDegraded'
OSPFINTERFACE_DOWN = 'OSPFInterfaceDown'
OSPFINTERFACE_DEGRADED = 'OSPFInterfaceDegraded'

# routing
DEFAULT_INTF_DOWN = 'DefaultInterfaceDown'
DEFAULT_ROUTER_DOWN = 'DefaultRouterDown'
DEFAULT_ROUTER_DEGRADED = 'DefaultRouterDegraded'
ACTIVE_DRAIN = 'ActiveDrain'

# fabric
ISL_DOWN = 'ISLDown'
ISL_DEGRADED = 'ISLDegraded'

# services
IRB_INTF_DOWN = 'IRBInterfaceDown'
IRB_INTF_DEGRADED = 'IRBInterfaceDegraded'
VXLAN_INTF_DOWN = 'VXLANInterfaceDown'
BRIDGE_INTF_DOWN = 'BridgeInterfaceDown'
BRIDGE_INTF_DEGRADED = 'BridgeInterfaceDegraded'
ROUTED_INTF_DOWN = 'RoutedInterfaceDown'
ROUTED_INTF_DEGRADED = 'RoutedInterfaceDegraded'
VLAN_DOWN = 'VLANDown'
VLAN_DEGRADED = 'VLANDegraded'
ROUTER_DOWN = 'RouterDown'
ROUTER_DEGRADED = 'RouterDegraded'
ROUTER_MEMBER_DOWN = 'RouterMemberDown'
BRIDGE_DOMAIN_DOWN = 'BridgeDomainDown'
BRIDGE_DOMAIN_DEGRADED = 'BridgeDomainDegraded'
BRIDGE_DOMAIN_MEMBER_DOWN = 'BridgeDomainMemberDown'

# interfaces
TRANS_HIGH_INPUT_POWER = 'TransceiverHighInputPower'
TRANS_HIGH_INPUT_POWER_WARNING = 'TransceiverHighInputPowerWarning'
TRANS_LOW_INPUT_POWER = 'TransceiverLowInputPower'
TRANS_LOW_INPUT_POWER_WARNING = 'TransceiverLowInputPowerWarning'
TRANS_HIGH_OUTPUT_POWER = 'TransceiverHighOutputPower'
TRANS_HIGH_OUTPUT_POWER_WARNING = 'TransceiverHighOutputPowerWarning'
TRANS_LOW_OUTPUT_POWER = 'TransceiverLowOutputPower'
TRANS_LOW_OUTPUT_POWER_WARNING = 'TransceiverLowOutputPowerWarning'
TRANS_HIGH_LASER_BIAS_CURRENT = 'TransceiverHighLaserBiasCurrent'
TRANS_HIGH_LASER_BIAS_CURRENT_WARNING = 'TransceiverHighLaserBiasCurrentWarning'
TRANS_LOW_LASER_BIAS_CURRENT = 'TransceiverLowLaserBiasCurrent'
TRANS_LOW_LASER_BIAS_CURRENT_WARNING = 'TransceiverLowLaserBiasCurrentWarning'
TRANS_HIGH_VOLTAGE = 'TransceiverHighVoltage'
TRANS_HIGH_VOLTAGE_WARNING = 'TransceiverHighVoltageWarning'
TRANS_LOW_VOLTAGE = 'TransceiverLowVoltage'
TRANS_LOW_VOLTAGE_WARNING = 'TransceiverLowVoltageWarning'
TRANS_HIGH_TEMPERATURE = 'TransceiverHighTemperature'
TRANS_HIGH_TEMPERATURE_WARNING = 'TransceiverHighTemperatureWarning'
TRANS_LOW_TEMPERATURE = 'TransceiverLowTemperature'
TRANS_LOW_TEMPERATURE_WARNING = 'TransceiverLowTemperatureWarning'
TRANS_CHANNEL_HIGH_INPUT_POWER = 'TransceiverChannelHighInputPower'
TRANS_CHANNEL_HIGH_INPUT_POWER_WARNING = 'TransceiverChannelHighInputPowerWarning'
TRANS_CHANNEL_LOW_INPUT_POWER = 'TransceiverChannelLowInputPower'
TRANS_CHANNEL_LOW_INPUT_POWER_WARNING = 'TransceiverChannelLowInputPowerWarning'
TRANS_CHANNEL_HIGH_OUTPUT_POWER = 'TransceiverChannelHighOutputPower'
TRANS_CHANNEL_HIGH_OUTPUT_POWER_WARNING = 'TransceiverChannelHighOutputPowerWarning'
TRANS_CHANNEL_LOW_OUTPUT_POWER = 'TransceiverChannelLowOutputPower'
TRANS_CHANNEL_LOW_OUTPUT_POWER_WARNING = 'TransceiverChannelLowOutputPowerWarning'
TRANS_CHANNEL_HIGH_LASER_BIAS_CURRENT = 'TransceiverChannelHighLaserBiasCurrent'
TRANS_CHANNEL_HIGH_LASER_BIAS_CURRENT_WARNING = 'TransceiverChannelHighLaserBiasCurrentWarning'
TRANS_CHANNEL_LOW_LASER_BIAS_CURRENT = 'TransceiverChannelLowLaserBiasCurrent'
TRANS_CHANNEL_LOW_LASER_BIAS_CURRENT_WARNING = 'TransceiverChannelLowLaserBiasCurrentWarning'
INTF_TRANS_DOWN = 'InterfaceTransceiverDown'
INTF_MEMBER_DOWN = 'InterfaceMemberDown'
INTF_DOWN = 'InterfaceDown'
INTF_DEGRADED = 'InterfaceDegraded'

# common
SUBINTF_DOWN = 'SubinterfaceDown'
BFD_SESSION_DOWN = "BFDSessionDown"
